# Generated by Django 6.0.1 on 2026-01-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
