# Generated by Django 6.0.1 on 2026-01-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_remove_appuser_email_remove_appuser_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='tasks',
            new_name='task',
        ),
    ]
